name: Teste de Integração Contínua com Cypress

on: push    # Execute este fluxo de trabalho sempre que um novo commit for enviado ou pull request for aberto.

jobs:
    cypress-run:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Configurar Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Instalar dependências
              run: npm install

            - name: Build do projeto
              run: npm run build

            - name: Executar testes Cypress
              run: npx cypress run

            - name: Upload de screenshots
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: cypress-screenshots
                path: cypress/screenshots
                if-no-files-found: ignore

            - name: Upload de vídeos
              uses: actions/upload-artifact@v4
              with:
                name: cypress-videos
                path: cypress/videos
                if-no-files-found: ignore